### PR TITLE
Backend danny

### PR DESCRIPTION
**Pull request by dannyyaou**
1. rename some folder
2. to connect to a database
3. 
file name conflict check

### CODE REVIEW

**Comment by YAANNY** [comment]
Cause our file name and file ID should be unique properties for each files, we have to deal with the name conflict

**Comment by YAANNY** [comment]
Can we search all the files through file list to get the related ID? is there any possibility for making conflicts in this way?

**Comment by dannyyaou** [comment]
Hi @YAANNY 
Thanks for asking

1. Can we search all the files through file list to get the related Id? is there any possibility for making conflicts in this way?

--> for id, you use get_all_file_details to get the id at first, and then you can get every update through websoccket

--> conflict is checked first before the uploaded file put in the server, so it won't happen again.

**Comment by YAANNY** [comment]
Thank you! I GOT IT!!!

**Pull request merged**
